name: ci

on:
  # 支持手动执行
  workflow_dispatch:

  # 每天凌晨一点（东八区）定时执行
  schedule:
    - cron: '0 17 * * *' # GitHub 使用 UTC 时间，东八区凌晨 1 点对应 UTC 17 点

  # 代码推送触发
  push:
    branches:
      - main # 限定为 main 分支
    paths:
      - trss-yunzai/Dockerfile
      - .github/workflows/publish.yml

env:
  TEST_TAG: wxyzhen/trss-yunzai:test
  LATEST_TAG: wxyzhen/trss-yunzai:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 设置 QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 构建和导出 Docker 镜像
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: trss-yunzai # 指定构建上下文
          file: trss-yunzai/Dockerfile # 指定 Dockerfile 路径
          load: true
          tags: ${{ env.TEST_TAG }}

      # 测试步骤
      - name: Test
        run: |
          docker run --rm -d -p2536:2536 ${{ env.TEST_TAG }}
          sleep 5
          curl -s http://localhost:2536/status || exit 1
          docker rm -f test-container

      # 构建并推送到 Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: trss-yunzai # 指定构建上下文
          file: trss-yunzai/Dockerfile # 指定 Dockerfile 路径
          #platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.TEST_TAG }}
